- name: Install haveged
  opkg:
    name: haveged
    state: present

- name: Enable haveged
  service:
    name: haveged
    state: started
    enabled: yes

- name: Configure system
  template:
    src: system.j2
    dest: "/etc/config/system"
