
- name: Install stubby
  opkg:
    name: stubby
    state: present

- name: Configure stubby
  copy:
    src: stubby
    dest: "/etc/config/stubby"
  register: stubbyconfigure

- name: Restart stubby
  when: stubbyconfigure.changed
  service:
    name: stubby
    state: restarted
    enabled: yes

- name: Enable stubby
  service:
    name: stubby
    state: started
    enabled: yes

- name: Install unbound
  opkg:
    name: unbound
    state: present

- name: Disable kresd
  service:
    name: kresd
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Remove knot
  opkg:
    name: knot-resolver
    state: absent

- name: Disable resolver service included in TurrisOS, it breaks unbound config
  service:
    name: resolver
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Configure unbound to use real config
  copy:
    src: unbound
    dest: "/etc/config/unbound"
  register: unbounduciconfigure

- name: Configure unbound
  template:
    src: unbound.conf.j2
    dest: "/etc/unbound/unbound.conf"
  register: unboundconfigure

- name: Restart unbound
  when: unboundconfigure.changed or unbounduciconfigure.changed
  service:
    name: unbound
    state: restarted
    enabled: yes